"""item counter statistics schema

Revision ID: 05f41a6f4568
Revises: e881925f34b5
Create Date: 2026-07-05 14:50:59.630784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05f41a6f4568'
down_revision: Union[str, Sequence[str], None] = 'e881925f34b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_counter_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patch_id', sa.Integer(), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('enemy_champion_id', sa.Integer(), nullable=False),
    sa.Column('enemy_role', sa.String(), nullable=False),
    sa.Column('games', sa.Integer(), nullable=False),
    sa.Column('picks', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('pick_rate', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['champion_id'], ['champions.champion_id'], ),
    sa.ForeignKeyConstraint(['enemy_champion_id'], ['champions.champion_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['patch_id'], ['patches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patch_id', 'champion_id', 'role', 'item_id', 'enemy_champion_id', 'enemy_role')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_counter_statistics')
    # ### end Alembic commands ###
