"""otp schema

Revision ID: 1533b701c9c7
Revises: 05f41a6f4568
Create Date: 2026-07-05 16:56:21.777398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1533b701c9c7'
down_revision: Union[str, Sequence[str], None] = '05f41a6f4568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puuid', sa.String(), nullable=False),
    sa.Column('primary_champion_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('patch_id', sa.Integer(), nullable=True),
    sa.Column('mastery_points', sa.Integer(), nullable=False),
    sa.Column('mastery_concentration', sa.Float(), nullable=False),
    sa.Column('games_sampled', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patch_id'], ['patches.id'], ),
    sa.ForeignKeyConstraint(['primary_champion_id'], ['champions.champion_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('puuid', 'primary_champion_id')
    )
    op.create_table('otp_builds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('otp_player_id', sa.Integer(), nullable=False),
    sa.Column('patch_id', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('win', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('starting_items', sa.JSON(), nullable=False),
    sa.Column('completed_items', sa.JSON(), nullable=False),
    sa.Column('final_items', sa.JSON(), nullable=False),
    sa.Column('primary_runes', sa.JSON(), nullable=False),
    sa.Column('secondary_runes', sa.JSON(), nullable=False),
    sa.Column('skill_order', sa.JSON(), nullable=False),
    sa.Column('enemy_champion_id', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['enemy_champion_id'], ['champions.champion_id'], ),
    sa.ForeignKeyConstraint(['otp_player_id'], ['otp_players.id'], ),
    sa.ForeignKeyConstraint(['patch_id'], ['patches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('otp_player_id', 'match_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('otp_builds')
    op.drop_table('otp_players')
    # ### end Alembic commands ###
