"""add item stats and build path columns

Revision ID: 53e4da1ea6a9
Revises: 99d897cfe6e7
Create Date: 2026-07-05 02:03:59.830000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53e4da1ea6a9'
down_revision: Union[str, Sequence[str], None] = '99d897cfe6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'items',
        sa.Column('stats', sa.JSON(), nullable=False, server_default='{}'),
    )
    op.add_column('items', sa.Column('depth', sa.Integer(), nullable=True))
    op.add_column(
        'items',
        sa.Column('builds_from', sa.JSON(), nullable=False, server_default='[]'),
    )
    op.add_column(
        'items',
        sa.Column('builds_into', sa.JSON(), nullable=False, server_default='[]'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'builds_into')
    op.drop_column('items', 'builds_from')
    op.drop_column('items', 'depth')
    op.drop_column('items', 'stats')
    # ### end Alembic commands ###
