"""add tips and source to champion_ability_details

Revision ID: 99d897cfe6e7
Revises: cdf5dcd79ddf
Create Date: 2026-07-05 01:24:53.905002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99d897cfe6e7'
down_revision: Union[str, Sequence[str], None] = 'cdf5dcd79ddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'champion_ability_details',
        sa.Column('tips', sa.String(), nullable=False, server_default=''),
    )
    op.add_column(
        'champion_ability_details',
        sa.Column('source', sa.String(), nullable=False, server_default='wiki'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('champion_ability_details', 'source')
    op.drop_column('champion_ability_details', 'tips')
    # ### end Alembic commands ###
