"""champion synergy and counters schema

Revision ID: b2f638ee5713
Revises: e5bd9398a31e
Create Date: 2026-07-05 12:12:10.995172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2f638ee5713'
down_revision: Union[str, Sequence[str], None] = 'e5bd9398a31e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('champion_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patch_id', sa.Integer(), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('enemy_champion_id', sa.Integer(), nullable=False),
    sa.Column('enemy_role', sa.String(), nullable=False),
    sa.Column('games', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['champion_id'], ['champions.champion_id'], ),
    sa.ForeignKeyConstraint(['enemy_champion_id'], ['champions.champion_id'], ),
    sa.ForeignKeyConstraint(['patch_id'], ['patches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patch_id', 'champion_id', 'role', 'enemy_champion_id', 'enemy_role')
    )
    op.create_table('champion_synergy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patch_id', sa.Integer(), nullable=False),
    sa.Column('champion_id_a', sa.Integer(), nullable=False),
    sa.Column('role_a', sa.String(), nullable=False),
    sa.Column('champion_id_b', sa.Integer(), nullable=False),
    sa.Column('role_b', sa.String(), nullable=False),
    sa.Column('games', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.CheckConstraint('champion_id_a < champion_id_b'),
    sa.ForeignKeyConstraint(['champion_id_a'], ['champions.champion_id'], ),
    sa.ForeignKeyConstraint(['champion_id_b'], ['champions.champion_id'], ),
    sa.ForeignKeyConstraint(['patch_id'], ['patches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patch_id', 'champion_id_a', 'role_a', 'champion_id_b', 'role_b')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('champion_synergy')
    op.drop_table('champion_counters')
    # ### end Alembic commands ###
