"""add item_wiki_details

Revision ID: c4f5fadd7a38
Revises: 53e4da1ea6a9
Create Date: 2026-07-05 02:10:20.315518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4f5fadd7a38'
down_revision: Union[str, Sequence[str], None] = '53e4da1ea6a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_wiki_details',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.Column('tips', sa.String(), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('raw_wikitext', sa.String(), nullable=False),
    sa.Column('wiki_title', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('patch_id', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['patch_id'], ['patches.id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_wiki_details')
    # ### end Alembic commands ###
