"""champion ability details

Revision ID: cdf5dcd79ddf
Revises: e32b4e86a12e
Create Date: 2026-07-04 17:33:43.699526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdf5dcd79ddf'
down_revision: Union[str, Sequence[str], None] = 'e32b4e86a12e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('champion_ability_details',
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('raw_wikitext', sa.String(), nullable=False),
    sa.Column('wiki_title', sa.String(), nullable=False),
    sa.Column('patch_id', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['champion_id'], ['champions.champion_id'], ),
    sa.ForeignKeyConstraint(['patch_id'], ['patches.id'], ),
    sa.PrimaryKeyConstraint('champion_id', 'slot')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('champion_ability_details')
    # ### end Alembic commands ###
