"""item and rune statistics schema

Revision ID: dec5b2201081
Revises: b2f638ee5713
Create Date: 2026-07-05 12:43:03.280016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dec5b2201081'
down_revision: Union[str, Sequence[str], None] = 'b2f638ee5713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patch_id', sa.Integer(), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('games', sa.Integer(), nullable=False),
    sa.Column('picks', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('pick_rate', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['champion_id'], ['champions.champion_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['patch_id'], ['patches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patch_id', 'champion_id', 'role', 'item_id')
    )
    op.create_table('rune_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patch_id', sa.Integer(), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('rune_id', sa.Integer(), nullable=False),
    sa.Column('is_keystone', sa.Boolean(), nullable=False),
    sa.Column('games', sa.Integer(), nullable=False),
    sa.Column('picks', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('pick_rate', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['champion_id'], ['champions.champion_id'], ),
    sa.ForeignKeyConstraint(['patch_id'], ['patches.id'], ),
    sa.ForeignKeyConstraint(['rune_id'], ['runes.rune_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patch_id', 'champion_id', 'role', 'rune_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rune_statistics')
    op.drop_table('item_statistics')
    # ### end Alembic commands ###
