"""knowledge schema

Revision ID: e32b4e86a12e
Revises: 
Create Date: 2026-07-04 16:49:00.308836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e32b4e86a12e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('champions',
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('riot_key', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('patch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patch_id'], ['patches.id'], ),
    sa.PrimaryKeyConstraint('champion_id'),
    sa.UniqueConstraint('riot_key')
    )
    op.create_table('items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('plaintext', sa.String(), nullable=True),
    sa.Column('gold_base', sa.Integer(), nullable=False),
    sa.Column('gold_total', sa.Integer(), nullable=False),
    sa.Column('gold_sell', sa.Integer(), nullable=False),
    sa.Column('patch_id', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['patch_id'], ['patches.id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('runes',
    sa.Column('rune_id', sa.Integer(), nullable=False),
    sa.Column('path_name', sa.String(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_desc', sa.String(), nullable=False),
    sa.Column('long_desc', sa.String(), nullable=False),
    sa.Column('patch_id', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['patch_id'], ['patches.id'], ),
    sa.PrimaryKeyConstraint('rune_id')
    )
    op.create_table('build_archetypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['champion_id'], ['champions.champion_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('champion_id', 'name')
    )
    op.create_table('champion_abilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.String(), nullable=False),
    sa.Column('ability_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('cooldown', sa.JSON(), nullable=True),
    sa.Column('cost', sa.JSON(), nullable=True),
    sa.Column('ability_range', sa.JSON(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['champion_id'], ['champions.champion_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('champion_id', 'slot')
    )
    op.create_table('champion_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('rating_name', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['champion_id'], ['champions.champion_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('champion_id', 'rating_name')
    )
    op.create_table('champion_stats',
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Float(), nullable=False),
    sa.Column('hp_per_level', sa.Float(), nullable=False),
    sa.Column('mp', sa.Float(), nullable=False),
    sa.Column('mp_per_level', sa.Float(), nullable=False),
    sa.Column('move_speed', sa.Float(), nullable=False),
    sa.Column('armor', sa.Float(), nullable=False),
    sa.Column('armor_per_level', sa.Float(), nullable=False),
    sa.Column('spell_block', sa.Float(), nullable=False),
    sa.Column('spell_block_per_level', sa.Float(), nullable=False),
    sa.Column('attack_range', sa.Float(), nullable=False),
    sa.Column('hp_regen', sa.Float(), nullable=False),
    sa.Column('hp_regen_per_level', sa.Float(), nullable=False),
    sa.Column('mp_regen', sa.Float(), nullable=False),
    sa.Column('mp_regen_per_level', sa.Float(), nullable=False),
    sa.Column('crit', sa.Float(), nullable=False),
    sa.Column('crit_per_level', sa.Float(), nullable=False),
    sa.Column('attack_damage', sa.Float(), nullable=False),
    sa.Column('attack_damage_per_level', sa.Float(), nullable=False),
    sa.Column('attack_speed_per_level', sa.Float(), nullable=False),
    sa.Column('attack_speed', sa.Float(), nullable=False),
    sa.Column('attack_rating', sa.Integer(), nullable=True),
    sa.Column('defense_rating', sa.Integer(), nullable=True),
    sa.Column('magic_rating', sa.Integer(), nullable=True),
    sa.Column('difficulty_rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['champion_id'], ['champions.champion_id'], ),
    sa.PrimaryKeyConstraint('champion_id')
    )
    op.create_table('champion_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['champion_id'], ['champions.champion_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('champion_id', 'tag', 'source')
    )
    op.create_table('item_effects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('effect_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'tag', 'source')
    )
    op.create_table('rune_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rune_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['rune_id'], ['runes.rune_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rune_id', 'tag', 'source')
    )
    op.create_table('archetype_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archetype_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('build_order', sa.Integer(), nullable=True),
    sa.Column('is_situational', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['archetype_id'], ['build_archetypes.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archetype_runes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archetype_id', sa.Integer(), nullable=False),
    sa.Column('rune_id', sa.Integer(), nullable=False),
    sa.Column('is_keystone', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['archetype_id'], ['build_archetypes.id'], ),
    sa.ForeignKeyConstraint(['rune_id'], ['runes.rune_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archetype_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archetype_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['archetype_id'], ['build_archetypes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('archetype_id', 'tag')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('archetype_tags')
    op.drop_table('archetype_runes')
    op.drop_table('archetype_items')
    op.drop_table('rune_tags')
    op.drop_table('item_tags')
    op.drop_table('item_effects')
    op.drop_table('champion_tags')
    op.drop_table('champion_stats')
    op.drop_table('champion_ratings')
    op.drop_table('champion_abilities')
    op.drop_table('build_archetypes')
    op.drop_table('runes')
    op.drop_table('items')
    op.drop_table('champions')
    op.drop_table('patches')
    # ### end Alembic commands ###
