"""riot api match schema

Revision ID: e5bd9398a31e
Revises: c4f5fadd7a38
Create Date: 2026-07-05 11:18:26.821816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5bd9398a31e'
down_revision: Union[str, Sequence[str], None] = 'c4f5fadd7a38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('patch_id', sa.Integer(), nullable=True),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('game_duration', sa.Integer(), nullable=False),
    sa.Column('game_creation', sa.DateTime(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['patch_id'], ['patches.id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('match_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('team_position', sa.String(), nullable=False),
    sa.Column('win', sa.Boolean(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['champion_id'], ['champions.champion_id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'champion_id')
    )
    op.create_table('matchup_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patch_id', sa.Integer(), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('games', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('picks', sa.Integer(), nullable=False),
    sa.Column('bans', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('pick_rate', sa.Float(), nullable=False),
    sa.Column('ban_rate', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['champion_id'], ['champions.champion_id'], ),
    sa.ForeignKeyConstraint(['patch_id'], ['patches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patch_id', 'champion_id', 'role')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matchup_statistics')
    op.drop_table('match_participants')
    op.drop_table('matches')
    # ### end Alembic commands ###
